//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADODBFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTION_INDICADORES_DETALLE
    {
        public decimal ID { get; set; }
        public string GESTION { get; set; }
        public string SUBGESTION { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> ANHO { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> DIA { get; set; }
        public Nullable<int> HORA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TXT_01 { get; set; }
        public string TXT_02 { get; set; }
        public string TXT_03 { get; set; }
        public string TXT_04 { get; set; }
        public string TXT_05 { get; set; }
        public string TXT_06 { get; set; }
        public string TXT_07 { get; set; }
        public string TXT_08 { get; set; }
        public string TXT_09 { get; set; }
        public string TXT_10 { get; set; }
        public string TXT_11 { get; set; }
        public string TXT_12 { get; set; }
        public Nullable<decimal> IDORIGEN { get; set; }
        public string DESCRIPCION_ORIGEN { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> TIEMPO { get; set; }
    }
}
