//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADODBFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTION_BASES
    {
        public decimal IDGESTION { get; set; }
        public string GESTION { get; set; }
        public string SUBGESTION { get; set; }
        public string CODI_GEST { get; set; }
        public string ID_ABONADO { get; set; }
        public Nullable<System.DateTime> FEC_TRAMITE { get; set; }
        public Nullable<System.DateTime> FEC_BAJA { get; set; }
        public Nullable<decimal> LLAMADAS_DIA { get; set; }
        public Nullable<decimal> LLAMADAS_ANT { get; set; }
        public Nullable<decimal> LLAMADAS_TOTAL { get; set; }
        public Nullable<decimal> CEF { get; set; }
        public Nullable<decimal> CNE { get; set; }
        public Nullable<decimal> NOC { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> VENTAS { get; set; }
        public string ESTADO { get; set; }
    }
}
