//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class APP_ACCESODTO
    {
        public Decimal IDACCESOAPP { get; set; }

        public Decimal IDAPP { get; set; }

        public Decimal IDROL { get; set; }

        public Decimal APPS_IDAPP { get; set; }

        public Decimal ROLES_IDROL { get; set; }

        public APP_ACCESODTO()
        {
        }

        public APP_ACCESODTO(Decimal iDACCESOAPP, Decimal iDAPP, Decimal iDROL, Decimal aPPS_IDAPP, Decimal rOLES_IDROL)
        {
			this.IDACCESOAPP = iDACCESOAPP;
			this.IDAPP = iDAPP;
			this.IDROL = iDROL;
			this.APPS_IDAPP = aPPS_IDAPP;
			this.ROLES_IDROL = rOLES_IDROL;
        }
    }
}
