//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 11:01:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class APPSDTO
    {
        public Decimal IDAPP { get; set; }

        public String CODAPP { get; set; }

        public String NOMAPP { get; set; }

        public String ESTADO { get; set; }

        public List<Decimal> APP_ACCESO_IDACCESOAPP { get; set; }

        public APPSDTO()
        {
        }

        public APPSDTO(Decimal iDAPP, String cODAPP, String nOMAPP, String eSTADO, List<Decimal> aPP_ACCESO_IDACCESOAPP)
        {
			this.IDAPP = iDAPP;
			this.CODAPP = cODAPP;
			this.NOMAPP = nOMAPP;
			this.ESTADO = eSTADO;
			this.APP_ACCESO_IDACCESOAPP = aPP_ACCESO_IDACCESOAPP;
        }
    }
}
