//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using ServiciosIndicadoresEntities;

namespace ServicioIndicadoresDTO
{

    /// <summary>
    /// Assembler for <see cref="GESTION_FILTROS"/> and <see cref="GESTION_FILTROSDTO"/>.
    /// </summary>
    public static partial class GESTION_FILTROSAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_FILTROSDTO"/> converted from <see cref="GESTION_FILTROS"/>.</param>
        static partial void OnDTO(this GESTION_FILTROS entity, GESTION_FILTROSDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_FILTROS"/> converted from <see cref="GESTION_FILTROSDTO"/>.</param>
        static partial void OnEntity(this GESTION_FILTROSDTO dto, GESTION_FILTROS entity);

        /// <summary>
        /// Converts this instance of <see cref="GESTION_FILTROSDTO"/> to an instance of <see cref="GESTION_FILTROS"/>.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_FILTROSDTO"/> to convert.</param>
        public static GESTION_FILTROS ToEntity(this GESTION_FILTROSDTO dto)
        {
            if (dto == null) return null;

            var entity = new GESTION_FILTROS();

            entity.IDFILTRO = dto.IDFILTRO;
            entity.CODOBJ = dto.CODOBJ;
            entity.CODFILTRO = dto.CODFILTRO;
            entity.FILTRO = dto.FILTRO;
            entity.APLICACION = dto.APLICACION;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="GESTION_FILTROS"/> to an instance of <see cref="GESTION_FILTROSDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_FILTROS"/> to convert.</param>
        public static GESTION_FILTROSDTO ToDTO(this GESTION_FILTROS entity)
        {
            if (entity == null) return null;

            var dto = new GESTION_FILTROSDTO();

            dto.IDFILTRO = entity.IDFILTRO;
            dto.CODOBJ = entity.CODOBJ;
            dto.CODFILTRO = entity.CODFILTRO;
            dto.FILTRO = entity.FILTRO;
            dto.APLICACION = entity.APLICACION;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_FILTROSDTO"/> to an instance of <see cref="GESTION_FILTROS"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<GESTION_FILTROS> ToEntities(this IEnumerable<GESTION_FILTROSDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_FILTROS"/> to an instance of <see cref="GESTION_FILTROSDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<GESTION_FILTROSDTO> ToDTOs(this IEnumerable<GESTION_FILTROS> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
