//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:07
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class GESTION_BASESDTO
    {
        public Decimal IDGESTION { get; set; }

        public String GESTION { get; set; }

        public String SUBGESTION { get; set; }

        public String CODI_GEST { get; set; }

        public String ID_ABONADO { get; set; }

        public Nullable<DateTime> FEC_TRAMITE { get; set; }

        public Nullable<DateTime> FEC_BAJA { get; set; }

        public Nullable<Decimal> LLAMADAS_DIA { get; set; }

        public Nullable<Decimal> LLAMADAS_ANT { get; set; }

        public Nullable<Decimal> LLAMADAS_TOTAL { get; set; }

        public Nullable<Decimal> CEF { get; set; }

        public Nullable<Decimal> CNE { get; set; }

        public Nullable<Decimal> NOC { get; set; }

        public String TIPO { get; set; }

        public Nullable<Decimal> VENTAS { get; set; }

        public String ESTADO { get; set; }

        public Nullable<Decimal> CONTPOT { get; set; }

        public Nullable<Decimal> LOGUEADOS { get; set; }

        public GESTION_BASESDTO()
        {
        }

        public GESTION_BASESDTO(Decimal iDGESTION, String gESTION, String sUBGESTION, String cODI_GEST, String iD_ABONADO, Nullable<DateTime> fEC_TRAMITE, Nullable<DateTime> fEC_BAJA, Nullable<Decimal> lLAMADAS_DIA, Nullable<Decimal> lLAMADAS_ANT, Nullable<Decimal> lLAMADAS_TOTAL, Nullable<Decimal> cEF, Nullable<Decimal> cNE, Nullable<Decimal> nOC, String tIPO, Nullable<Decimal> vENTAS, String eSTADO, Nullable<Decimal> cONTPOT, Nullable<Decimal> lOGUEADOS)
        {
			this.IDGESTION = iDGESTION;
			this.GESTION = gESTION;
			this.SUBGESTION = sUBGESTION;
			this.CODI_GEST = cODI_GEST;
			this.ID_ABONADO = iD_ABONADO;
			this.FEC_TRAMITE = fEC_TRAMITE;
			this.FEC_BAJA = fEC_BAJA;
			this.LLAMADAS_DIA = lLAMADAS_DIA;
			this.LLAMADAS_ANT = lLAMADAS_ANT;
			this.LLAMADAS_TOTAL = lLAMADAS_TOTAL;
			this.CEF = cEF;
			this.CNE = cNE;
			this.NOC = nOC;
			this.TIPO = tIPO;
			this.VENTAS = vENTAS;
			this.ESTADO = eSTADO;
			this.CONTPOT = cONTPOT;
			this.LOGUEADOS = lOGUEADOS;
        }
    }
}
