//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class GESTION_CONF_VARIABLESDTO
    {
        public Decimal IDVARIABLE { get; set; }

        public String CODVAR { get; set; }

        public String NOMVAR { get; set; }

        public String CALC { get; set; }

        public String FORMULA { get; set; }

        public String UNIDAD { get; set; }

        public String ESTADO { get; set; }

        public GESTION_CONF_VARIABLESDTO()
        {
        }

        public GESTION_CONF_VARIABLESDTO(Decimal iDVARIABLE, String cODVAR, String nOMVAR, String cALC, String fORMULA, String uNIDAD, String eSTADO)
        {
			this.IDVARIABLE = iDVARIABLE;
			this.CODVAR = cODVAR;
			this.NOMVAR = nOMVAR;
			this.CALC = cALC;
			this.FORMULA = fORMULA;
			this.UNIDAD = uNIDAD;
			this.ESTADO = eSTADO;
        }
    }
}
