//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class GESTION_FILTROSDTO
    {
        public Decimal IDFILTRO { get; set; }

        public String CODOBJ { get; set; }

        public String CODFILTRO { get; set; }

        public String FILTRO { get; set; }

        public String APLICACION { get; set; }

        public GESTION_FILTROSDTO()
        {
        }

        public GESTION_FILTROSDTO(Decimal iDFILTRO, String cODOBJ, String cODFILTRO, String fILTRO, String aPLICACION)
        {
			this.IDFILTRO = iDFILTRO;
			this.CODOBJ = cODOBJ;
			this.CODFILTRO = cODFILTRO;
			this.FILTRO = fILTRO;
			this.APLICACION = aPLICACION;
        }
    }
}
