//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 11:01:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using ServiciosIndicadoresEntities;

namespace ServicioIndicadoresDTO
{

    /// <summary>
    /// Assembler for <see cref="GESTION_BASES"/> and <see cref="GESTION_BASESDTO"/>.
    /// </summary>
    public static partial class GESTION_BASESAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_BASESDTO"/> converted from <see cref="GESTION_BASES"/>.</param>
        static partial void OnDTO(this GESTION_BASES entity, GESTION_BASESDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_BASES"/> converted from <see cref="GESTION_BASESDTO"/>.</param>
        static partial void OnEntity(this GESTION_BASESDTO dto, GESTION_BASES entity);

        /// <summary>
        /// Converts this instance of <see cref="GESTION_BASESDTO"/> to an instance of <see cref="GESTION_BASES"/>.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_BASESDTO"/> to convert.</param>
        public static GESTION_BASES ToEntity(this GESTION_BASESDTO dto)
        {
            if (dto == null) return null;

            var entity = new GESTION_BASES();

            entity.IDGESTION = dto.IDGESTION;
            entity.GESTION = dto.GESTION;
            entity.SUBGESTION = dto.SUBGESTION;
            entity.CODI_GEST = dto.CODI_GEST;
            entity.ID_ABONADO = dto.ID_ABONADO;
            entity.FEC_TRAMITE = dto.FEC_TRAMITE;
            entity.FEC_BAJA = dto.FEC_BAJA;
            entity.LLAMADAS_DIA = dto.LLAMADAS_DIA;
            entity.LLAMADAS_ANT = dto.LLAMADAS_ANT;
            entity.LLAMADAS_TOTAL = dto.LLAMADAS_TOTAL;
            entity.CEF = dto.CEF;
            entity.CNE = dto.CNE;
            entity.NOC = dto.NOC;
            entity.TIPO = dto.TIPO;
            entity.VENTAS = dto.VENTAS;
            entity.ESTADO = dto.ESTADO;
            entity.CONTPOT = dto.CONTPOT;
            entity.LOGUEADOS = dto.LOGUEADOS;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="GESTION_BASES"/> to an instance of <see cref="GESTION_BASESDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_BASES"/> to convert.</param>
        public static GESTION_BASESDTO ToDTO(this GESTION_BASES entity)
        {
            if (entity == null) return null;

            var dto = new GESTION_BASESDTO();

            dto.IDGESTION = entity.IDGESTION;
            dto.GESTION = entity.GESTION;
            dto.SUBGESTION = entity.SUBGESTION;
            dto.CODI_GEST = entity.CODI_GEST;
            dto.ID_ABONADO = entity.ID_ABONADO;
            dto.FEC_TRAMITE = entity.FEC_TRAMITE;
            dto.FEC_BAJA = entity.FEC_BAJA;
            dto.LLAMADAS_DIA = entity.LLAMADAS_DIA;
            dto.LLAMADAS_ANT = entity.LLAMADAS_ANT;
            dto.LLAMADAS_TOTAL = entity.LLAMADAS_TOTAL;
            dto.CEF = entity.CEF;
            dto.CNE = entity.CNE;
            dto.NOC = entity.NOC;
            dto.TIPO = entity.TIPO;
            dto.VENTAS = entity.VENTAS;
            dto.ESTADO = entity.ESTADO;
            dto.CONTPOT = entity.CONTPOT;
            dto.LOGUEADOS = entity.LOGUEADOS;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_BASESDTO"/> to an instance of <see cref="GESTION_BASES"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<GESTION_BASES> ToEntities(this IEnumerable<GESTION_BASESDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_BASES"/> to an instance of <see cref="GESTION_BASESDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<GESTION_BASESDTO> ToDTOs(this IEnumerable<GESTION_BASES> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
