//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/12 - 11:01:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using ServiciosIndicadoresEntities;

namespace ServicioIndicadoresDTO
{

    /// <summary>
    /// Assembler for <see cref="GESTION_INDICADORES_DETALLE"/> and <see cref="GESTION_INDICADORES_DETALLEDTO"/>.
    /// </summary>
    public static partial class GESTION_INDICADORES_DETALLEAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_INDICADORES_DETALLEDTO"/> converted from <see cref="GESTION_INDICADORES_DETALLE"/>.</param>
        static partial void OnDTO(this GESTION_INDICADORES_DETALLE entity, GESTION_INDICADORES_DETALLEDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_INDICADORES_DETALLE"/> converted from <see cref="GESTION_INDICADORES_DETALLEDTO"/>.</param>
        static partial void OnEntity(this GESTION_INDICADORES_DETALLEDTO dto, GESTION_INDICADORES_DETALLE entity);

        /// <summary>
        /// Converts this instance of <see cref="GESTION_INDICADORES_DETALLEDTO"/> to an instance of <see cref="GESTION_INDICADORES_DETALLE"/>.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_INDICADORES_DETALLEDTO"/> to convert.</param>
        public static GESTION_INDICADORES_DETALLE ToEntity(this GESTION_INDICADORES_DETALLEDTO dto)
        {
            if (dto == null) return null;

            var entity = new GESTION_INDICADORES_DETALLE();

            entity.ID = dto.ID;
            entity.GESTION = dto.GESTION;
            entity.SUBGESTION = dto.SUBGESTION;
            entity.TIPO = dto.TIPO;
            entity.ANHO = dto.ANHO;
            entity.MES = dto.MES;
            entity.DIA = dto.DIA;
            entity.HORA = dto.HORA;
            entity.FECHA = dto.FECHA;
            entity.TXT_01 = dto.TXT_01;
            entity.TXT_02 = dto.TXT_02;
            entity.TXT_03 = dto.TXT_03;
            entity.TXT_04 = dto.TXT_04;
            entity.TXT_05 = dto.TXT_05;
            entity.TXT_06 = dto.TXT_06;
            entity.TXT_07 = dto.TXT_07;
            entity.TXT_08 = dto.TXT_08;
            entity.TXT_09 = dto.TXT_09;
            entity.TXT_10 = dto.TXT_10;
            entity.TXT_11 = dto.TXT_11;
            entity.TXT_12 = dto.TXT_12;
            entity.IDORIGEN = dto.IDORIGEN;
            entity.DESCRIPCION_ORIGEN = dto.DESCRIPCION_ORIGEN;
            entity.CANTIDAD = dto.CANTIDAD;
            entity.TIEMPO = dto.TIEMPO;
            entity.TXT_13 = dto.TXT_13;
            entity.TXT_14 = dto.TXT_14;
            entity.TXT_15 = dto.TXT_15;
            entity.VAL_01 = dto.VAL_01;
            entity.VAL_02 = dto.VAL_02;
            entity.VAL_03 = dto.VAL_03;
            entity.VAL_04 = dto.VAL_04;
            entity.VAL_05 = dto.VAL_05;
            entity.VAL_06 = dto.VAL_06;
            entity.VAL_07 = dto.VAL_07;
            entity.VAL_08 = dto.VAL_08;
            entity.VAL_09 = dto.VAL_09;
            entity.VAL_10 = dto.VAL_10;
            entity.VAL_11 = dto.VAL_11;
            entity.VAL_12 = dto.VAL_12;
            entity.VAL_13 = dto.VAL_13;
            entity.VAL_14 = dto.VAL_14;
            entity.VAL_15 = dto.VAL_15;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="GESTION_INDICADORES_DETALLE"/> to an instance of <see cref="GESTION_INDICADORES_DETALLEDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_INDICADORES_DETALLE"/> to convert.</param>
        public static GESTION_INDICADORES_DETALLEDTO ToDTO(this GESTION_INDICADORES_DETALLE entity)
        {
            if (entity == null) return null;

            var dto = new GESTION_INDICADORES_DETALLEDTO();

            dto.ID = entity.ID;
            dto.GESTION = entity.GESTION;
            dto.SUBGESTION = entity.SUBGESTION;
            dto.TIPO = entity.TIPO;
            dto.ANHO = entity.ANHO;
            dto.MES = entity.MES;
            dto.DIA = entity.DIA;
            dto.HORA = entity.HORA;
            dto.FECHA = entity.FECHA;
            dto.TXT_01 = entity.TXT_01;
            dto.TXT_02 = entity.TXT_02;
            dto.TXT_03 = entity.TXT_03;
            dto.TXT_04 = entity.TXT_04;
            dto.TXT_05 = entity.TXT_05;
            dto.TXT_06 = entity.TXT_06;
            dto.TXT_07 = entity.TXT_07;
            dto.TXT_08 = entity.TXT_08;
            dto.TXT_09 = entity.TXT_09;
            dto.TXT_10 = entity.TXT_10;
            dto.TXT_11 = entity.TXT_11;
            dto.TXT_12 = entity.TXT_12;
            dto.IDORIGEN = entity.IDORIGEN;
            dto.DESCRIPCION_ORIGEN = entity.DESCRIPCION_ORIGEN;
            dto.CANTIDAD = entity.CANTIDAD;
            dto.TIEMPO = entity.TIEMPO;
            dto.TXT_13 = entity.TXT_13;
            dto.TXT_14 = entity.TXT_14;
            dto.TXT_15 = entity.TXT_15;
            dto.VAL_01 = entity.VAL_01;
            dto.VAL_02 = entity.VAL_02;
            dto.VAL_03 = entity.VAL_03;
            dto.VAL_04 = entity.VAL_04;
            dto.VAL_05 = entity.VAL_05;
            dto.VAL_06 = entity.VAL_06;
            dto.VAL_07 = entity.VAL_07;
            dto.VAL_08 = entity.VAL_08;
            dto.VAL_09 = entity.VAL_09;
            dto.VAL_10 = entity.VAL_10;
            dto.VAL_11 = entity.VAL_11;
            dto.VAL_12 = entity.VAL_12;
            dto.VAL_13 = entity.VAL_13;
            dto.VAL_14 = entity.VAL_14;
            dto.VAL_15 = entity.VAL_15;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_INDICADORES_DETALLEDTO"/> to an instance of <see cref="GESTION_INDICADORES_DETALLE"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<GESTION_INDICADORES_DETALLE> ToEntities(this IEnumerable<GESTION_INDICADORES_DETALLEDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_INDICADORES_DETALLE"/> to an instance of <see cref="GESTION_INDICADORES_DETALLEDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<GESTION_INDICADORES_DETALLEDTO> ToDTOs(this IEnumerable<GESTION_INDICADORES_DETALLE> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
