//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using ServiciosIndicadoresEntities;

namespace ServicioIndicadoresDTO
{

    /// <summary>
    /// Assembler for <see cref="GESTION_INDICADORES_RESUMEN"/> and <see cref="GESTION_INDICADORES_RESUMENDTO"/>.
    /// </summary>
    public static partial class GESTION_INDICADORES_RESUMENAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_INDICADORES_RESUMENDTO"/> converted from <see cref="GESTION_INDICADORES_RESUMEN"/>.</param>
        static partial void OnDTO(this GESTION_INDICADORES_RESUMEN entity, GESTION_INDICADORES_RESUMENDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_INDICADORES_RESUMEN"/> converted from <see cref="GESTION_INDICADORES_RESUMENDTO"/>.</param>
        static partial void OnEntity(this GESTION_INDICADORES_RESUMENDTO dto, GESTION_INDICADORES_RESUMEN entity);

        /// <summary>
        /// Converts this instance of <see cref="GESTION_INDICADORES_RESUMENDTO"/> to an instance of <see cref="GESTION_INDICADORES_RESUMEN"/>.
        /// </summary>
        /// <param name="dto"><see cref="GESTION_INDICADORES_RESUMENDTO"/> to convert.</param>
        public static GESTION_INDICADORES_RESUMEN ToEntity(this GESTION_INDICADORES_RESUMENDTO dto)
        {
            if (dto == null) return null;

            var entity = new GESTION_INDICADORES_RESUMEN();

            entity.IDRESUMEN = dto.IDRESUMEN;
            entity.CODOBJ = dto.CODOBJ;
            entity.ANHO = dto.ANHO;
            entity.MES = dto.MES;
            entity.DIA = dto.DIA;
            entity.FECHA = dto.FECHA;
            entity.CODVAR = dto.CODVAR;
            entity.DESCRIPCION = dto.DESCRIPCION;
            entity.VALOR = dto.VALOR;
            entity.VALOROBJ = dto.VALOROBJ;
            entity.LIMA = dto.LIMA;
            entity.PROVINCIA = dto.PROVINCIA;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="GESTION_INDICADORES_RESUMEN"/> to an instance of <see cref="GESTION_INDICADORES_RESUMENDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="GESTION_INDICADORES_RESUMEN"/> to convert.</param>
        public static GESTION_INDICADORES_RESUMENDTO ToDTO(this GESTION_INDICADORES_RESUMEN entity)
        {
            if (entity == null) return null;

            var dto = new GESTION_INDICADORES_RESUMENDTO();

            dto.IDRESUMEN = entity.IDRESUMEN;
            dto.CODOBJ = entity.CODOBJ;
            dto.ANHO = entity.ANHO;
            dto.MES = entity.MES;
            dto.DIA = entity.DIA;
            dto.FECHA = entity.FECHA;
            dto.CODVAR = entity.CODVAR;
            dto.DESCRIPCION = entity.DESCRIPCION;
            dto.VALOR = entity.VALOR;
            dto.VALOROBJ = entity.VALOROBJ;
            dto.LIMA = entity.LIMA;
            dto.PROVINCIA = entity.PROVINCIA;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_INDICADORES_RESUMENDTO"/> to an instance of <see cref="GESTION_INDICADORES_RESUMEN"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<GESTION_INDICADORES_RESUMEN> ToEntities(this IEnumerable<GESTION_INDICADORES_RESUMENDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="GESTION_INDICADORES_RESUMEN"/> to an instance of <see cref="GESTION_INDICADORES_RESUMENDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<GESTION_INDICADORES_RESUMENDTO> ToDTOs(this IEnumerable<GESTION_INDICADORES_RESUMEN> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
