//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class GESTION_VARIABLESDTO
    {
        public Decimal IDVARIABLE { get; set; }

        public String CODOBJ { get; set; }

        public String CODI_GEST { get; set; }

        public String GESTION { get; set; }

        public String SUBGESTION { get; set; }

        public String CODVAR { get; set; }

        public String NOMVAR { get; set; }

        public Nullable<Decimal> VALOR { get; set; }

        public String UNIDAD { get; set; }

        public String ESTADO { get; set; }

        public GESTION_VARIABLESDTO()
        {
        }

        public GESTION_VARIABLESDTO(Decimal iDVARIABLE, String cODOBJ, String cODI_GEST, String gESTION, String sUBGESTION, String cODVAR, String nOMVAR, Nullable<Decimal> vALOR, String uNIDAD, String eSTADO)
        {
			this.IDVARIABLE = iDVARIABLE;
			this.CODOBJ = cODOBJ;
			this.CODI_GEST = cODI_GEST;
			this.GESTION = gESTION;
			this.SUBGESTION = sUBGESTION;
			this.CODVAR = cODVAR;
			this.NOMVAR = nOMVAR;
			this.VALOR = vALOR;
			this.UNIDAD = uNIDAD;
			this.ESTADO = eSTADO;
        }
    }
}
