//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/09 - 20:59:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class ROLESDTO
    {
        public Decimal IDROL { get; set; }

        public String CODROL { get; set; }

        public String NOMROL { get; set; }

        public String ESTADO { get; set; }

        public List<Decimal> APP_ACCESO_IDACCESOAPP { get; set; }

        public List<Decimal> USUARIOS_IDUSUARIO { get; set; }

        public ROLESDTO()
        {
        }

        public ROLESDTO(Decimal iDROL, String cODROL, String nOMROL, String eSTADO, List<Decimal> aPP_ACCESO_IDACCESOAPP, List<Decimal> uSUARIOS_IDUSUARIO)
        {
			this.IDROL = iDROL;
			this.CODROL = cODROL;
			this.NOMROL = nOMROL;
			this.ESTADO = eSTADO;
			this.APP_ACCESO_IDACCESOAPP = aPP_ACCESO_IDACCESOAPP;
			this.USUARIOS_IDUSUARIO = uSUARIOS_IDUSUARIO;
        }
    }
}
