//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/16 - 11:41:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ServicioIndicadoresDTO
{
    public partial class sysdiagramsDTO
    {
        public String name { get; set; }

        public Int32 principal_id { get; set; }

        public Int32 diagram_id { get; set; }

        public Nullable<Int32> version { get; set; }

        public Byte[] definition { get; set; }

        public sysdiagramsDTO()
        {
        }

        public sysdiagramsDTO(String name, Int32 principal_id, Int32 diagram_id, Nullable<Int32> version, Byte[] definition)
        {
			this.name = name;
			this.principal_id = principal_id;
			this.diagram_id = diagram_id;
			this.version = version;
			this.definition = definition;
        }
    }
}
