//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014/02/08 - 23:05:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace AccesoDatosDTO
{
    public partial class GESTION_INDICADORES_DETALLEDTO
    {
        public Decimal ID { get; set; }

        public String GESTION { get; set; }

        public String SUBGESTION { get; set; }

        public String TIPO { get; set; }

        public Nullable<Int32> ANHO { get; set; }

        public Nullable<Int32> MES { get; set; }

        public Nullable<Int32> DIA { get; set; }

        public Nullable<Int32> HORA { get; set; }

        public Nullable<DateTime> FECHA { get; set; }

        public String TXT_01 { get; set; }

        public String TXT_02 { get; set; }

        public String TXT_03 { get; set; }

        public String TXT_04 { get; set; }

        public String TXT_05 { get; set; }

        public String TXT_06 { get; set; }

        public String TXT_07 { get; set; }

        public String TXT_08 { get; set; }

        public String TXT_09 { get; set; }

        public String TXT_10 { get; set; }

        public String TXT_11 { get; set; }

        public String TXT_12 { get; set; }

        public Nullable<Decimal> IDORIGEN { get; set; }

        public String DESCRIPCION_ORIGEN { get; set; }

        public Nullable<Decimal> CANTIDAD { get; set; }

        public Nullable<Decimal> TIEMPO { get; set; }

        public GESTION_INDICADORES_DETALLEDTO()
        {
        }

        public GESTION_INDICADORES_DETALLEDTO(Decimal iD, String gESTION, String sUBGESTION, String tIPO, Nullable<Int32> aNHO, Nullable<Int32> mES, Nullable<Int32> dIA, Nullable<Int32> hORA, Nullable<DateTime> fECHA, String tXT_01, String tXT_02, String tXT_03, String tXT_04, String tXT_05, String tXT_06, String tXT_07, String tXT_08, String tXT_09, String tXT_10, String tXT_11, String tXT_12, Nullable<Decimal> iDORIGEN, String dESCRIPCION_ORIGEN, Nullable<Decimal> cANTIDAD, Nullable<Decimal> tIEMPO)
        {
			this.ID = iD;
			this.GESTION = gESTION;
			this.SUBGESTION = sUBGESTION;
			this.TIPO = tIPO;
			this.ANHO = aNHO;
			this.MES = mES;
			this.DIA = dIA;
			this.HORA = hORA;
			this.FECHA = fECHA;
			this.TXT_01 = tXT_01;
			this.TXT_02 = tXT_02;
			this.TXT_03 = tXT_03;
			this.TXT_04 = tXT_04;
			this.TXT_05 = tXT_05;
			this.TXT_06 = tXT_06;
			this.TXT_07 = tXT_07;
			this.TXT_08 = tXT_08;
			this.TXT_09 = tXT_09;
			this.TXT_10 = tXT_10;
			this.TXT_11 = tXT_11;
			this.TXT_12 = tXT_12;
			this.IDORIGEN = iDORIGEN;
			this.DESCRIPCION_ORIGEN = dESCRIPCION_ORIGEN;
			this.CANTIDAD = cANTIDAD;
			this.TIEMPO = tIEMPO;
        }
    }
}
