
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiciosIndicadoresEntities
{

using System;
    using System.Collections.Generic;
    
public partial class APP_ACCESO
{

    public decimal IDACCESOAPP { get; set; }

    public decimal IDAPP { get; set; }

    public decimal IDROL { get; set; }



    public virtual APPS APPS { get; set; }

    public virtual ROLES ROLES { get; set; }

}

}
