//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosIndicadoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPS
    {
        public APPS()
        {
            this.APP_ACCESO = new HashSet<APP_ACCESO>();
        }
    
        public decimal IDAPP { get; set; }
        public string CODAPP { get; set; }
        public string NOMAPP { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<APP_ACCESO> APP_ACCESO { get; set; }
    }
}
