//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosIndicadoresEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndicadoresEntities : DbContext
    {
        public IndicadoresEntities()
            : base("name=IndicadoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APP_ACCESO> APP_ACCESO { get; set; }
        public DbSet<APPS> APPS { get; set; }
        public DbSet<GESTION_BASES> GESTION_BASES { get; set; }
        public DbSet<GESTION_INDICADORES_DETALLE> GESTION_INDICADORES_DETALLE { get; set; }
        public DbSet<ROLES> ROLES { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<GESTION_CONF_VARIABLES> GESTION_CONF_VARIABLES { get; set; }
        public DbSet<GESTION_VARIABLES> GESTION_VARIABLES { get; set; }
        public DbSet<GESTION_INDICADORES_RESUMEN> GESTION_INDICADORES_RESUMEN { get; set; }
    }
}
