//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosIndicadoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTION_VARIABLES
    {
        public decimal IDVARIABLE { get; set; }
        public string CODOBJ { get; set; }
        public string CODI_GEST { get; set; }
        public string GESTION { get; set; }
        public string SUBGESTION { get; set; }
        public string CODVAR { get; set; }
        public string NOMVAR { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string UNIDAD { get; set; }
        public string ESTADO { get; set; }
    }
}
