//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosIndicadoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTION_INDICADORES_RESUMEN
    {
        public decimal IDRESUMEN { get; set; }
        public string CODOBJ { get; set; }
        public Nullable<decimal> ANHO { get; set; }
        public Nullable<decimal> MES { get; set; }
        public Nullable<decimal> DIA { get; set; }
        public Nullable<decimal> FECHA { get; set; }
        public string CODVAR { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<decimal> VALOROBJ { get; set; }
        public Nullable<decimal> LIMA { get; set; }
        public Nullable<decimal> PROVINCIA { get; set; }
    }
}
