//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosIndicadoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTION_FILTROS
    {
        public decimal IDFILTRO { get; set; }
        public string CODOBJ { get; set; }
        public string CODFILTRO { get; set; }
        public string FILTRO { get; set; }
    }
}
