//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosIndicadoresEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public ROLES()
        {
            this.APP_ACCESO = new HashSet<APP_ACCESO>();
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public decimal IDROL { get; set; }
        public string CODROL { get; set; }
        public string NOMROL { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<APP_ACCESO> APP_ACCESO { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
