
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiciosIndicadoresEntities
{

using System;
    using System.Collections.Generic;
    
public partial class USUARIOS
{

    public decimal IDUSUARIO { get; set; }

    public string CODUSUARIO { get; set; }

    public string APEPAT { get; set; }

    public string APEMAT { get; set; }

    public string NOMBRE { get; set; }

    public string EMAIL { get; set; }

    public string DIRECCION { get; set; }

    public string DNI { get; set; }

    public string PASSWORD { get; set; }

    public Nullable<decimal> IDROL { get; set; }



    public virtual ROLES ROLES { get; set; }

}

}
